### ISSUE TITLE
Steam版零之轨迹改（英文版）反汇编报错

### ISSUE THREAD

**Issue by not94** [Ouroboros/Falcom#1]
Hello，在尝试使用零之轨迹的[Decompiler](https://github.com/Ouroboros/Falcom/tree/master/Decompiler)将Steam版零之轨迹改（英文版）下的scena文件夹反汇编的时候有KeyError的报错：
```
disasm /mnt/c/Program Files (x86)/Steam/steamapps/common/The Legend of Heroes Trails from Zero/data/scena_us/00sys.bin
disasm /mnt/c/Program Files (x86)/Steam/steamapps/common/The Legend of Heroes Trails from Zero/data/scena_us/a0000.bin
Traceback (most recent call last):
  File "EDDecompiler/Decompiler/ZeroScenarioScript.py", line 1485, in <module>
    procfile(file)
  File "EDDecompiler/Decompiler/ZeroScenarioScript.py", line 1457, in procfile
    scena.open(file)
  File "EDDecompiler/Decompiler/ZeroScenarioScript.py", line 959, in open
    self.CodeBlocks = self.DisassembleBlocks(fs)
  File "EDDecompiler/Decompiler/ZeroScenarioScript.py", line 1074, in DisassembleBlocks
    block = disasm.DisasmBlock2(data)
  File "/home/crazyleaves/zeroTrails/EDDecompiler/Decompiler/Assembler/Assembler2s.py", line 85, in DisasmBlock2
    self.DisasmBlockWorker(disasmdata)
  File "/home/crazyleaves/zeroTrails/EDDecompiler/Decompiler/Assembler/Assembler2s.py", line 220, in DisasmBlockWorker
    newblock = self.DisasmBlock2(newdata)
  File "/home/crazyleaves/zeroTrails/EDDecompiler/Decompiler/Assembler/Assembler2s.py", line 85, in DisasmBlock2
    self.DisasmBlockWorker(disasmdata)
  File "/home/crazyleaves/zeroTrails/EDDecompiler/Decompiler/Assembler/Assembler2s.py", line 220, in DisasmBlockWorker
    newblock = self.DisasmBlock2(newdata)
  File "/home/crazyleaves/zeroTrails/EDDecompiler/Decompiler/Assembler/Assembler2s.py", line 85, in DisasmBlock2
    self.DisasmBlockWorker(disasmdata)
  File "/home/crazyleaves/zeroTrails/EDDecompiler/Decompiler/Assembler/Assembler2s.py", line 220, in DisasmBlockWorker
    newblock = self.DisasmBlock2(newdata)
  File "/home/crazyleaves/zeroTrails/EDDecompiler/Decompiler/Assembler/Assembler2s.py", line 85, in DisasmBlock2
    self.DisasmBlockWorker(disasmdata)
  File "/home/crazyleaves/zeroTrails/EDDecompiler/Decompiler/Assembler/Assembler2s.py", line 192, in DisasmBlockWorker
    inst = DisasmInstruction(handlerdata)
  File "/home/crazyleaves/zeroTrails/EDDecompiler/Decompiler/Assembler/Assembler2s.py", line 150, in DisasmInstruction
    entry = InstructionTable[op]
KeyError: 255/
```

感觉零之轨迹改和零之轨迹使用了不同的指令所以无法适配，但是00sys.bin是能够反汇编解析成py文件，想要咨询下Decompiler是否支持零之轨迹改的反汇编？

**Comment by Ouroboros** [comment]
不支持

https://github.com/Kyuuhachi/Aureole

可以用这个
